version: "3.9"  # optional since v1.27.0
services:
  discovery-service:
    container_name: discovery-service
    build: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      - DISCOVER_SERVICE_HOST=discovery-service
      - DISCOVER_SERVICE_PORT=8761

  user-service:
    container_name: user-service
    build: ./user-service
    environment:
      - DISCOVER_SERVICE_HOST=discovery-service
      - DISCOVER_SERVICE_PORT=8761
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8082:8082"
    environment:
      - DISCOVER_SERVICE_HOST=discovery-service
      - DISCOVER_SERVICE_PORT=8761


