server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVER_SERVICE_HOST:localhost}:${DISCOVER_SERVICE_PORT:8761}/eureka

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: user-service

gateway:
  ip: ${GATEWAY_IP:192.168.1.13}

token:
  expiration_time: 300000
  secret: cisco



logging:
  level:
    root: INFO
    com.app.cisco.ciscoservice: INFO
